name: Generate PDF
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: continuity-in-tt.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: continuity-in-tt.pdf
